<?php

namespace Database\Seeders;

use App\Models\Admin\Portfolio;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PortfolioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $portfolios = [
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Random Consortium',
                'category_id' => 1,
                'title' => 'ALCOHOL TESTING',
                'section_image' => '1738734163-alcohol_testing.png',
                'portfolio_slug' => 'alcohol-testing',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 50,
                'created_at' => '2025-02-05 05:07:53',
                'updated_at' => '2025-02-05 05:42:43',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'DOT Supervisor Training',
                'category_id' => 3,
                'title' => 'HAIR DRUG TESTING',
                'section_image' => '1738734430-hairtest-1.jpg',
                'portfolio_slug' => 'hair-drug-testing',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 60,
                'created_at' => '2025-02-05 05:47:10',
                'updated_at' => '2025-02-05 05:47:10',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'DOT Testing',
                'category_id' => 4,
                'title' => 'BAT - REGULATED',
                'section_image' => '1738734493-urine-test.jpg',
                'portfolio_slug' => 'bat-regulated',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 70,
                'created_at' => '2025-02-05 05:48:13',
                'updated_at' => '2025-02-05 05:48:13',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'DOT Testing',
                'category_id' => 4,
                'title' => 'DOT DRUG PANEL W/TS',
                'section_image' => '1738734430-hairtest-1.jpg',
                'portfolio_slug' => 'dot-drug-panel-w-ts',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 80,
                'created_at' => '2025-02-05 05:48:13',
                'updated_at' => '2025-02-05 05:48:13',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'DOT Supervisor Training',
                'category_id' => 3,
                'title' => 'DOT TESTING',
                'section_image' => '1738734516-dot_testing.png',
                'portfolio_slug' => 'dot-testing',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 90,
                'created_at' => '2025-02-05 05:48:36',
                'updated_at' => '2025-02-05 05:48:36',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Background Checks',
                'category_id' => 2,
                'title' => 'OCCUPATIONAL HEALTH TESTING',
                'section_image' => '1738734537-ocupational.jpeg',
                'portfolio_slug' => 'occupational-health-testing',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 100,
                'created_at' => '2025-02-05 05:48:57',
                'updated_at' => '2025-02-05 05:48:57',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'DOT Supervisor Training',
                'category_id' => 3,
                'title' => 'LAB/BLOODTESTING',
                'section_image' => '1738734555-lab_testing.jpg',
                'portfolio_slug' => 'lab-bloodtesting',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 110,
                'created_at' => '2025-02-05 05:49:15',
                'updated_at' => '2025-02-05 05:49:15',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Random Consortium',
                'category_id' => 1,
                'title' => 'DNA-PATERNITYTESTING',
                'section_image' => '1738734570-dna_testing.jpg',
                'portfolio_slug' => 'dna-paternitytesting',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 120,
                'created_at' => '2025-02-05 05:49:30',
                'updated_at' => '2025-02-05 05:49:30',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'Rapid 5-Panel Test',
                'section_image' => '1738734587-Onsite-Van-45.png',
                'portfolio_slug' => 'rapid-5-panel-test',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 130,
                'created_at' => '2025-02-05 05:49:47',
                'updated_at' => '2025-02-05 05:49:47',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'Express Results 10 panel',
                'section_image' => '',
                'portfolio_slug' => 'express-results-10-panel',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 140,
                'created_at' => '2025-02-05 05:49:47',
                'updated_at' => '2025-02-05 05:49:47',
            ],
            
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 7-50/2000+6AM',
                'section_image' => '',
                'portfolio_slug' => 'sap-7-50-2000-6am',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 160,
                'created_at' => '2025-02-12 10:58:43',
                'updated_at' => '2025-02-12 10:58:43',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 9-50/2K',
                'section_image' => '',
                'portfolio_slug' => 'sap-9-50-2k',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 170,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 10-50/2K',
                'section_image' => '',
                'portfolio_slug' => 'sap-10-50-2k',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 190,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'DOT LOOKALIKE',
                'section_image' => '',
                'portfolio_slug' => 'dot-lookalike',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 200,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 5-50/2000+6AM/TS',
                'section_image' => '',
                'portfolio_slug' => 'sap-5-50-2000-6am-ts',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 210,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'HAIR-5',
                'section_image' => '',
                'portfolio_slug' => 'hair-5',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 220,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'HAIR-5 (EXOP)',
                'section_image' => '',
                'portfolio_slug' => 'hair-5-exop',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 230,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'Oral fluid',
                'section_image' => '',
                'portfolio_slug' => 'oral-fluid',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 240,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 4/2000 W/NIT',
                'section_image' => '',
                'portfolio_slug' => 'sap-4-2000-w-nit',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 250,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 6/2000 W/NIT',
                'section_image' => '',
                'portfolio_slug' => 'sap-6-2000-w-nit',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 260,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 9/2000 W/NIT',
                'section_image' => '',
                'portfolio_slug' => 'sap-9-2000-w-nit',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 270,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 7-50/SYOP+6AM/TS',
                'section_image' => '',
                'portfolio_slug' => 'sap-7-50-syop-6am-ts',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 280,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 9-50/SYOP+6AM/TS',
                'section_image' => '',
                'portfolio_slug' => 'sap-9-50-syop-6am-ts',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 290,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 10-50/SYOP+6AM/TS',
                'section_image' => '',
                'portfolio_slug' => 'sap-10-50-syop-6am-ts',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 300,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 5-50+MDMA/6AM/T',
                'section_image' => '',
                'portfolio_slug' => 'sap-5-50-mdma-6am-t',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 310,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 7-50+MDMA/6AM/T',
                'section_image' => '',
                'portfolio_slug' => 'sap-7-50-mdma-6am-t',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 320,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 9-50+MDA/6AM/T',
                'section_image' => '',
                'portfolio_slug' => 'sap-9-50-mdma-6am-t',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 330,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 10-50+MDMA/6AM/T',
                'section_image' => '',
                'portfolio_slug' => 'sap-10-50-mdma-6am-t',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 340,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 5-50 W/OPI+6AM/T',
                'section_image' => '',
                'portfolio_slug' => 'sap-5-50-w-opi-6am-t',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 350,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 7-50 W/OPI+6AM/T',
                'section_image' => '',
                'portfolio_slug' => 'sap-7-50-w-opi-6am-t',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 360,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 9-50 W/OPI+6AM/T',
                'section_image' => '',
                'portfolio_slug' => 'sap-9-50-w-opi-6am-t',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 370,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],
            [
                'language_id' => 1,
                'style' => 'style1',
                'category_name' => 'Non DOT Testing',
                'category_id' => 5,
                'title' => 'SAP 10-50 W/OPI+6A/T',
                'section_image' => '',
                'portfolio_slug' => 'sap-10-50-w-opi-6am-t',
                'status' => 'published',
                'url' => 0,
                'order' => 0,
                'price'=> 380,
                'created_at' => '2025-02-12 10:59:05',
                'updated_at' => '2025-02-12 10:59:05',
            ],


        ];

        Portfolio::insert($portfolios);
    }
}
